# Spring boot application
spring:
  application:
    name: dubbo-auto-configuration-provider-demo
  # Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
dubbo:
  scan:
    base-packages: sl.demo.dubbo.provider.service

  # Dubbo Application
  ## The default value of dubbo.application.name is ${spring.application.name}
  ## dubbo.application.name=${spring.application.name}

  # Dubbo Protocol
  protocol:
    name: dubbo
    port: 12345

  ## Dubbo Registry
  registry:
    address: N/A